=== sighani/SENG202_KaiTech/Project_2019_S2/resources/dtd/suppliers.dtd
<!-- DTD for representing suppliers -->
<!-- (C) Neville Churcher 2019 -->
<!ENTITY version "V0.01 (C) Neville Churcher 2019">
<!ELEMENT suppliers (description, (supplier*))>
<!ELEMENT description (#PCDATA)>
<!ELEMENT supplier (sid, name, address, phone, email?, url?)>
<!ELEMENT sid (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ATTLIST phone type (mobile|work|home) #REQUIRED>
<!ELEMENT email (#PCDATA)>
<!ELEMENT url (#PCDATA)>

=== sighani/SENG202_KaiTech/resources/data/Suppliers.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE suppliers SYSTEM "../dtd/suppliers.dtd">
<suppliers>
    <description>Some sample supplier data</description>
    <supplier>
        <sid>s1</sid>
        <name>Countup</name>
        <address>12 High Street, Christchurch</address>
        <phone type="work">3451234</phone>
        <email>daveG@countup.co.nz</email>
        <url>countup.co.nz/high</url>
    </supplier>
    <supplier>
        <sid>s2</sid>
        <name>Funky Kumquat</name>
        <address>125 Woodside Lane, Christchurch</address>
        <phone type="mobile">021352176</phone>
        <email>maryC@fkveg.co.nz</email>
    </supplier>
    <supplier>
        <sid>s3</sid>
        <name>Admiral Benjamin's Seafoods</name>
        <address>86 Low Street, Christchurch</address>
        <phone type="mobile">021345666</phone>
        <email>bigben@cfoods.co.nz</email>
        <url>cfoods.co.nz</url>
    </supplier>
    <supplier>
        <sid>s4</sid>
        <name>Dave's Drinks</name>
        <address>Unit 5, Bert's Business Park, Christchurch</address>
        <phone type="work">3515666</phone>
        <email>daved@davesdrinks.co.nz</email>
        <url></url>
    </supplier>
</suppliers>
